# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58544b1a05bff493c93a4284d020b962b1b2327ab593275606fb093419eaeac27230fc3305ca1855a78cf9f7101dfcc142187d62ba9e346dffe2e5d6e5f80b27

test:
  secret_key_base: 0047dc003d867884f139602fe5f0483300c823fb408106cda598b56fbbc914197bd850de89d318cc3e5075dcdb1cfa262912cfb09170a1bf7c1beefffb1a4379

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
